name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    env:
      GO111MODULE: 'off'
      GOPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: ./src
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Go Mod
      run: |
        go get github.com/therecipe/qt/core
        go get github.com/therecipe/qt/gui
        go get github.com/therecipe/qt/widgets

    - name: BuildCLi
      run: |
        cd src/cmd
        go build -v

    - name: Get Qt binding for Go
      run: go get -v github.com/therecipe/qt/cmd/...
    - uses: actions/cache@v2
      id: cache-qt-bindings-win
      with:
        path: ${{ github.workspace }}/src/github.com/therecipe
        key: cache-qt-bindings-win
    - name: Generate Qt bindings
      if: ${{ steps.cache-qt-bindings-win.outputs.cache-hit != 'true' }}
      run: ${{ env.GOPATH }}/bin/qtsetup -test=false

    - name: BuildGUI
      run: |
        cd src/gui
        ${{ env.GOPATH }}/bin/qtdeploy build desktop
        
    - name: tree0
      run: dir src/cmd
    - name: tree1
      run: dir src/gui
    - name: tree2
      run: dir src/gui/deploy

    - name: Upload build artifacts1
      uses: actions/upload-artifact@v2
      with:
        path: .src/cmd/cmd.exe
        
    - name: Upload build artifacts2
      uses: actions/upload-artifact@v2
      with:
        path: .src/gui/gui.exe
