name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    #- name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      #run: echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
      #shell: bash
      
    - name: Go Mod
      run: |
        go mod init github.com/hpxro7/wwiseutil
        go get github.com/therecipe/qt/core
        go get github.com/therecipe/qt/gui
        go get github.com/therecipe/qt/widgets
    #- name: show GOPATH
    #  run: echo "${{ env.GOPATH }}"
      
    - name: BuildCLi
      run: |
        cd cmd
        go build -v
      #env:
      #  GOPATH: "${{ env.GOPATH }}"

    - name: BuildGUI
      run: |
        cd gui
        go build -v
      #env:
      #  GOPATH: "${{ env.GOPATH }}"
        
    - name: tree1
      run: dir gui

    - name: Upload build artifacts1
      uses: actions/upload-artifact@v2
      with:
        path: ./cmd/cmd.exe
        
    - name: Upload build artifacts2
      uses: actions/upload-artifact@v2
      with:
        path: ./gui/gui.exe
