name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go Mod
      run: go mod init github.com/hpxro7/wwiseutil
    - name: tree11
      run: pwd
    - name: aaa
      run: echo $GITHUB_WORKSPACE
    - name: tree12
      run: |
        cd cmd
        go build -v

    #- name: BuildCLi
    #  run: go build -v
      
    #- name: BuildGUI
    #  run: go build -v gui
      
    - name: tree1
      run: dir

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: All
        path: ./
