name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    env:
      GO111MODULE: 'off'
      GOPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: VVVVV
      run: echo "${{ env.GOPATH }}"
      
    - name: Go Mod
      run: |
        go get github.com/hpxro7/wwiseutil
        go get github.com/therecipe/qt/core
        go get github.com/therecipe/qt/gui
        go get github.com/therecipe/qt/widgets
    - name: xxx
      run: tree "${{ env.GOPATH }}"
    - name: xxx
      run: dir "${{ env.GOPATH }}"
    - name: BuildCLi
      run: |
        cd cmd
        go build -v

    - name: BuildGUI
      run: |
        cd gui
        go build -v
        
    - name: tree1
      run: dir gui

    - name: Upload build artifacts1
      uses: actions/upload-artifact@v2
      with:
        path: ./cmd/cmd.exe
        
    - name: Upload build artifacts2
      uses: actions/upload-artifact@v2
      with:
        path: ./gui/gui.exe
