name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    env:
      GO111MODULE: 'off'
      GOPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: ./src
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: VVVVV
      run: echo "${{ env.GOPATH }}"
      
    - name: Go Mod
      run: |
        go get github.com/therecipe/qt/core
        go get github.com/therecipe/qt/gui
        go get github.com/therecipe/qt/widgets
    - name: Get Qt binding for Go
      run: go get -v github.com/therecipe/qt/cmd/...
    - name: Generate Qt bindings
      run: $(go env GOPATH)/bin/qtsetup -test=false
    - name: xxx
      run: tree "${{ env.GOPATH }}"
      shell: pwsh
    - name: xxx
      run: dir "${{ env.GOPATH }}"
    - name: tree2
      run: dir
    - name: BuildCLi
      run: |
        cd src/cmd
        go build -v
    - name: Get dependencies
      run: |
        cd src/gui
        $(go env GOPATH)/bin/qtmoc
    - name: BuildGUI
      run: |
        cd src/gui
        $(go env GOPATH)/bin/qtdeploy build windows_64_static
        
    - name: tree1
      run: dir src/gui

    - name: tree3
      run: dir 
    - name: Upload build artifacts1
      uses: actions/upload-artifact@v2
      with:
        path: ./cmd/cmd.exe
        
    - name: Upload build artifacts2
      uses: actions/upload-artifact@v2
      with:
        path: ./gui/gui.exe
